services:
- docker
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- eval $(aws ecr get-login --no-include-email --region us-west-1) 
- curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | 
  sudo tee -a /usr/bin/ecs-deploy
- sudo chmod +x /usr/bin/ecs-deploy
- docker-compose build
- docker tag phillipxkang/kim-cheeze:latest 746836633374.dkr.ecr.us-west-1.amazonaws.com/phillipxkang/kim-cheeze:latest
- docker push 746836633374.dkr.ecr.us-west-1.amazonaws.com/phillipxkang/kim-cheeze:latest
- ecs-deploy -c krab -n main-service -i phillipxkang/kim-cheeze:latest
env:
  global:
  - secure: nDCecqVDOccqq4EKQmpLa88ORhdO5jmmCyBDuB9nbCOjfXk1Mtx0hfhx+GUaH0fqlgCqDrnBLkP7Lx5zqLU9saPaW3xsKznTEfn4dh5B3jGpk4+54MrH5rWKXtojv1hrWPcZ+8pgnPwZJNEdR98i14w9oJYw0q5cWSfnL7TnPfmaOVVzlrlv5j9eFVDxqcFmr6CvxW0GbZr7nrGt25rkOboQy4OtkjzHC0ckn85o7hGMfweh4EuqukEqRxOcyGAhnKoZ39zBQXcs4SgfDAQaSQPYxkR0gdoXXG1NStvGBV07GLkWNl9Na4pJKIYHLKbJ1Po1hO6EXjTIQ0J/kHnQ9tTDU+uXj7cX5dTnWRKx186TMBHHBvKA4MRg7hU0WEqgjJiui5NKlDXwQGbJ9swFWeo+rig39p/LCrBVPZdz10hsU8KDPUy/F7VDh75NGgV5lBr2LqIuc/kb4DA2lSrhn2XLLaQxqW8YUE0eNou6SpU/18hvuDL0p3fIR7TUSrwF5CE2GYbSoWRjvuCHabyrkyebPnvXyei2nYV5YcBHiyqfsqM14RZG9tXPimyY2xN/iDTjeUgqiyI/QDQH71O5vRFQ8EqUOSpYt+JKt2h9clnX61G4eRs2eI+WxZGFPj+XyHX8LschszX8ZWNVdGdMTiu8q1osSpgxVebb9eWwd8E=
  - secure: HDVbN8C668NPq7DhFGV/B8TAziwaNintSGdCnHp+nspN/cs+pwVdrGxo5PGrYnUuCEZFrXXc8YlBh8R9nMLyZuPACj03/rHb/9SZcA489/Z82cIVjyIACK4kUtwsrnYU39dBpTcqUrqJghe8oTyChs30f1Xka8xWveNEfEUdnzMACjP4Dd9RR7L1/POUeqhiUmq73byOjBH5DavbTBuW6sKk2kDaDpwshzpxyURJ+S15z/UJhJXIe+kfRaaPfaaXhzWWSc2xYWMJ0Yp0NxvfohL1jTZ1J/a5OPZxwzGzymOMGFiGEkAEUAS+B5xf6WfFfDMf3FMfeSP6Hs7Ib4NwANl0yN8Pklg2Epb5IbX5rAyRViivVEvLSXbZQAHAvNa3C1Lp4fhPE0GF6zlOKT5TJb8FznSgHuwVM6Ky/j16KsuGdZYnZvBKkes38eoylDBHwsesKxYUMf/Ztu3u8lDMosHggN6is7VqBAspQ0aRDky3ZBlA9wyAKxOVXbJPTcSik2uLEGhH5djcetw324aVNC8wTJiLF66z4h0DVH9ma/ftLcsgYdZuGUqGncjf8RbRqENA3D65Yn8Js2M9NcEzUCS0sB7l0RwtAAhqKHNpPZxbowfUnfT4IQWVPZOqf1OrYF4fzEgxITr8I9eGwqg6vm1wl21+/2sJxeno264b/zU=
  - AWS_DEFAULT_REGION=us-west-1